version: "3"

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 2345:5432
    environment:
      POSTGRES_PASSWORD: "dashboard-password"
      POSTGRES_USER: "dashboard-user"
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - data:/var/lib/postgresql-dashboard/data
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=admin
      - MONGO_INITDB_ROOT_USERNAME=mongo_dashboard_user
      - MONGO_INITDB_ROOT_PASSWORD=mongo_dashboard_password
    volumes:
      - mongo_data:/data/db
  # redis:
  #   container_name: dashboard-redis
  #   image: redis
  #   ports:
  #   - "6379:6379"

volumes:
  data:
    external: false
  mongo_data:
    external: false