version: "3"

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 2345:5432
    environment:
      POSTGRES_PASSWORD: "dashboard-password"
      POSTGRES_USER: "dashboard-user"
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - data:/var/lib/postgresql-dashboard/data
  redis:
    container_name: dashboard-redis
    image: redis
    ports:
    - "6379:6379"

volumes:
  data:
    external: false